### ISSUE TITLE
Yew example doesn't build

### ISSUE THREAD

**Issue by marcopio72** [ctron/popper-rs#1]
There are many errors during build.
It is configured to use yew 0.21 but the code uses functions that are no longer available for example use_effect_with_deps

```
src\example\basic.rs:65:5
    |
65  |       use_effect_with_deps(
    |       ^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `use_effect_with`
```
Marco

**Comment by ctron** [comment]
That was also missing from the CI … thanks for reporting this, will fix!
